name: Generate Learn.Core.Shared.Models

on:
  push:
    branches: [ master ]
    paths:
      - 'Core/Learn.Core.Shared.Models/**'
      - '.github/workflows/main.yml'
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
    
jobs:
  use-template:
    uses: hugocorreia77/IaC/.github/workflows/main.yml@main
    with:
      project-name: Learn.Core.Shared.Models
      project-path: Core/Learn.Core.Shared.Models
    secrets:
      NUGET_SOURCE: ${{ secrets.NUGET_SOURCE }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      
