name: Use Template

on:
  push:
    branches: [ master ]

jobs:
  use-template:
    uses: hugocorreia77/IaC/.github/workflows/main.yml@main
    with:
      project-name: Learn.Core.Shared
      project-path: Core/Learn.Core.Shared/Learn.Core.Shared.csproj
