name: Use Template

on:
  push:
    branches: [ master ]

jobs:
  use-template:
    uses: hugocorreia77/IaC/tree/main/.github/workflows/template-build-net8.yml@main
    with:
      project-name: Learn.Core.Shared
